# this config file contains all config fields with comments
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
# patch the generated kubeadm config with some extra settings
kubeadmConfigPatches:
- |
  apiVersion: kubeadm.k8s.io/v1beta3
  kind: ClusterConfiguration
  metadata:
    name: config
  etcd:
    local:
      extraArgs:
        # Don't forget quotes on values
        client-cert-auth: "false"
        trusted-ca-file: ""
# 1 control plane node and 3 workers
nodes:
# the control plane node config
- role: control-plane
