#!/usr/bin/env ansible-playbook
---
- name: Start up a kind cluster
  hosts: localhost
  vars:
    cluster_name: etcdnoauth
    # This needs to be the cluster name with -control-plane added 
    container_name: etcdnoauth-control-plane
    cluster_config: etcd-noauth.yml
    kubernetes_version: v1.30.0

  tasks:
  - import_tasks: ./ansible_tasks/setup_kind_custom_config.yaml
  

- name: Setup Cluster
  hosts: etcdnoauth-control-plane
  connection: docker
  vars:
    ansible_python_interpreter: /usr/bin/python3
    
  tasks:
  - import_tasks: ./ansible_tasks/setup_kubeconfig.yml
  - import_tasks: ./ansible_tasks/print_cluster_ip.yml
  - import_tasks: ./ansible_tasks/create_cluster_admin_service_account.yaml