#!/usr/bin/env ansible-playbook
---
- name: Start up a kind cluster
  hosts: localhost
  vars:
    cluster_name: rwkubeletnoauth
    # This needs to be the cluster name with -control-plane added 
    container_name: rwkubeletnoauth-control-plane
    cluster_config: rwkubelet.yml
    kubernetes_version: v1.18.2

  tasks:
  - import_tasks: ./ansible_tasks/setup_kind_custom_config.yaml 

- name: Setup Cluster
  hosts: rwkubeletnoauth-control-plane
  connection: docker
  vars:
    ansible_python_interpreter: /usr/bin/python3
    
  tasks:
  - import_tasks: ./ansible_tasks/setup_kubeconfig.yml
  - import_tasks: ./ansible_tasks/print_cluster_ip.yml