#!/usr/bin/env ansible-playbook
---
- name: Start up a kind cluster
  hosts: localhost
  vars:
    cluster_name: sshcdh
    # This needs to be the cluster name with -control-plane added 
    container_name: sshcdh-control-plane

  tasks:
    - name: Start a kind cluster
      command: kind create cluster --name {{ cluster_name }}
    - name: Add the host
      add_host: name={{ container_name }}

  # This needs to be in place for every playbook using kind as we need Python
- name: install Python in the cluster
  hosts: sshcdh-control-plane
  connection: docker
  gather_facts: no

  tasks:
  - import_tasks: ./ansible_tasks/install_python.yml
  

- name: Setup Cluster
  hosts: sshcdh-control-plane
  connection: docker

  tasks:
  - import_tasks: ./ansible_tasks/setup_kubeconfig.yml
  - import_tasks: ./ansible_tasks/setup_ssh_pod.yml
    
  - name: Copy Role Manifest
    copy: 
      src: ./manifests/daemonset-creator.yml
      dest: /root

  - name: Apply Role Manifest
    command: kubectl create -f /root/daemonset-creator.yml

  - name: Give the default service account rights to manage daemonsets
    command: kubectl create rolebinding serviceaccounts-daemonset-manager --role=daemonset-creator --group=system:serviceaccounts
  
  - import_tasks: ./ansible_tasks/print_cluster_ip.yml