#!/usr/bin/env ansible-playbook
---
- name: Start up a kind cluster
  hosts: localhost
  vars:
    cluster_name: sshcdh
    # This needs to be the cluster name with -control-plane added 
    container_name: sshcdh-control-plane
    kubernetes_version: v1.30.0

  tasks:
  - import_tasks: ./ansible_tasks/setup_kind_standard_config.yaml

- name: Setup Cluster
  hosts: sshcdh-control-plane
  connection: docker
  vars:
    ansible_python_interpreter: /usr/bin/python3
    
  tasks:
  - import_tasks: ./ansible_tasks/setup_kubeconfig.yml
  - import_tasks: ./ansible_tasks/setup_ssh_pod.yml
    
  - name: Copy Role Manifest
    copy: 
      src: ./manifests/daemonset-creator.yml
      dest: /root

  - name: Apply Role Manifest
    command: kubectl create -f /root/daemonset-creator.yml

  - name: Give the default service account rights to manage daemonsets
    command: kubectl create rolebinding serviceaccounts-daemonset-manager --role=daemonset-creator --group=system:serviceaccounts
  
  - import_tasks: ./ansible_tasks/print_cluster_ip.yml