#!/usr/bin/env ansible-playbook
---
- name: Start up a kind cluster
  hosts: localhost
  vars:
    cluster_name: sshcm
    # This needs to be the cluster name with -control-plane added 
    container_name: sshcm-control-plane
    kubernetes_version: v1.30.0

  tasks:
  - import_tasks: ./ansible_tasks/setup_kind_standard_config.yaml
  
- name: Setup Cluster
  hosts: sshcm-control-plane
  connection: docker
  vars:
    ansible_python_interpreter: /usr/bin/python3
    
  tasks:
  - import_tasks: ./ansible_tasks/setup_kubeconfig.yml
  - import_tasks: ./ansible_tasks/setup_ssh_pod.yml
  - import_tasks: ./ansible_tasks/make_default_service_account_cluster_admin.yaml 
  - import_tasks: ./ansible_tasks/print_cluster_ip.yml