#!/usr/bin/env ansible-playbook
---
- name: Start up a kind cluster
  hosts: localhost
  vars:
    cluster_name: sshgs
    # This needs to be the cluster name with -control-plane added 
    container_name: sshgs-control-plane

  tasks:
    - name: Start a kind cluster
      command: kind create cluster --name {{ cluster_name }}
    - name: Add the host
      add_host: name={{ container_name }}

  # This needs to be in place for every playbook using kind as we need Python
- name: install Python in the cluster
  hosts: sshgs-control-plane
  connection: docker
  gather_facts: no

  tasks:
  - import_tasks: ./ansible_tasks/install_python.yml
  

- name: Setup Cluster
  hosts: sshgs-control-plane
  connection: docker

  tasks:
  - import_tasks: ./ansible_tasks/setup_kubeconfig.yml
  - import_tasks: ./ansible_tasks/setup_ssh_pod.yml
    
  - name: Copy Role Manifest
    copy: 
      src: ./manifests/secret-reader.yml
      dest: /root

  - name: Apply Role Manifest
    command: kubectl create -f /root/secret-reader.yml

  - name: Give the default service account rights to manage pods
    command: kubectl create clusterrolebinding serviceaccounts-secret-reader --clusterrole=secret-reader --group=system:serviceaccounts

  - import_tasks: ./ansible_tasks/print_cluster_ip.yml