#!/usr/bin/env ansible-playbook
---
- name: Start up a kind cluster
  hosts: localhost
  vars:
    cluster_name: tillernoauth
    # This needs to be the cluster name with -control-plane added 
    container_name: tillernoauth-control-plane
    kubernetes_version: v1.30.0

  tasks:
   - import_tasks: ./ansible_tasks/setup_kind_standard_config.yaml

  

- name: Setup Cluster
  hosts: tillernoauth-control-plane
  connection: docker
  vars:
    ansible_python_interpreter: /usr/bin/python3
    
  tasks:
  - import_tasks: ./ansible_tasks/setup_kubeconfig.yml
  - import_tasks: ./ansible_tasks/install_helm.yml
  - import_tasks: ./ansible_tasks/setup_helm.yml
    
  - name: Expose Tiller via NodePort
    command: kubectl patch svc tiller-deploy -n kube-system --type='json' -p '[{"op":"replace","path":"/spec/type","value":"NodePort"}]'
  
  - import_tasks: ./ansible_tasks/print_cluster_ip.yml